name: Run tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - name: Install SDL2
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev

    - name: Build VM
      run: cargo build

    - name: Test VM
      run: RUST_BACKTRACE=1 cargo test

    - name: Test plush command-line arguments
      working-directory: .
      run: |
        cargo run tests/empty.pls
        cargo run tests/fact.pls
        cargo run examples/helloworld.pls
        cargo run examples/print_int.pls
        cargo run examples/fib.pls
    #    cargo run -- -o output_file.asm examples/chess.c
    #    cargo run -- -E examples/crc32.c > /dev/null
